api_key: "P3bR2oc3Dte2GCtcYvpAkbytTnR7iWSC"
base_url: "http://127.0.0.1:8384"
icon_mode: "emoji"  # Options: "emoji" or "nerdfont"
path_map:
  "/data": "/home/jeff/sync"
  "/photos": "/home/jeff/Photos"

